import { defineStore } from 'pinia'
export const productsStore = defineStore('products', {
    state: () => ({
        products: [
            {
                id: 1,
                title: "Видеокарта MSI GeForce 210 [N210-1GD3/LP] [PCI-E 2.0 1 ГБ GDDR3, 64 бит, DVI-I, HDMI, VGA (D-Sub), GPU 460 МГц]",
                oldPrice: 2800,
                newPrice: 2600,
                isPopular: true,
                sale: 25,
                brand: "MSI",
                size: 1,
                quantity: 1,
            },
            {
                id: 2,
                title: "Видеокарта KFA2 GeForce 210 [21GGF4HI00NK] [PCI-E 2.0 1 ГБ GDDR3, 64 бит, DVI-I, HDMI, VGA (D-Sub), GPU 520 МГц]",
                oldPrice: 3000,
                newPrice: 2800,
                isPopular: false,
                sale: 20,
                brand: "KFA2",
                size: 2,
                quantity: 0,
            },
            {
                id: 3,
                title: "Видеокарта ASUS GeForce GT 710 [GT710-SL-2GD5] [PCI-E 2.0 2 ГБ GDDR5, 64 бит, HDMI, DVI-D, VGA (D-Sub), GPU 954 МГц]",
                oldPrice: 4000,
                newPrice: 3700,
                isPopular: true,
                sale: 15,
                brand: "ASUS",
                size: 3,
                quantity: 2,
            },
            {
                id: 4,
                title: "Видеокарта GIGABYTE GeForce GT 1030 [GV-N1030D5-2GL] [PCI-E 3.0 2 ГБ GDDR5, 64 бит, HDMI, DVI-D, GPU 1252 МГц]",
                oldPrice: 5000,
                newPrice: 4500,
                isPopular: true,
                sale: 10,
                brand: "GIGABYTE",
                size: 4,
                quantity: 3,
            },
            {
                id: 5,
                title: "Видеокарта ZOTAC GeForce GTX 1650 [ZT-T16500H-10L] [PCI-E 3.0 4 ГБ GDDR6, 128 бит, HDMI, DP, GPU 1410 МГц]",
                oldPrice: 12000,
                newPrice: 11000,
                isPopular: true,
                sale: 8,
                brand: "ZOTAC",
                size: 5,
                quantity: 4,
            },
            {
                id: 6,
                title: "Видеокарта Palit GeForce GTX 1660 [NE51660018J9-165F] [PCI-E 3.0 6 ГБ GDDR5, 192 бит, HDMI, DP, DVI-D, GPU 1530 МГц]",
                oldPrice: 15000,
                newPrice: 14000,
                isPopular: false,
                sale: 5,
                brand: "Palit",
                size: 6,
                quantity: 10,
            },
            {
                id: 7,
                title: "Видеокарта ASUS ROG Strix Radeon RX 570 [STRIX-RX570-4G-GAMING] [PCI-E 3.0 4 ГБ GDDR5, 256 бит, HDMI, DP, DVI-D, GPU 1256 МГц]",
                oldPrice: 13000,
                newPrice: 12000,
                isPopular: true,
                sale: 10,
                brand: "ASUS",
                size: 1,
                quantity: 10,
            },
            {
                id: 8,
                title: "Видеокарта Sapphire Pulse Radeon RX 580 [11265-05-20G] [PCI-E 3.0 8 ГБ GDDR5, 256 бит, HDMI, DP, DVI-D, GPU 1257 МГц]",
                oldPrice: 17000,
                newPrice: 16000,
                isPopular: true,
                sale: 6,
                brand: "Sapphire",
                size: 2,
                quantity: 10,
            },
            {
                id: 9,
                title: "Видеокарта MSI GeForce RTX 2060 [RTX 2060 VENTUS XS 6G OC] [PCI-E 3.0 6 ГБ GDDR6, 192 бит, HDMI, DP, GPU 1365 МГц]",
                oldPrice: 24000,
                newPrice: 22000,
                isPopular: true,
                sale: 10,
                brand: "MSI",
                size: 3,
                quantity: 10,
            },
            {
                id: 10,
                title: "Видеокарта ASUS TUF Gaming GeForce RTX 3070 [TUF-RTX3070-O8G-GAMING] [PCI-E 4.0 8 ГБ GDDR6, 256 бит, HDMI, DP, GPU 1500 МГц]",
                oldPrice: 70000,
                newPrice: 65000,
                isPopular: true,
                sale: 7,
                brand: "ASUS",
                size: 4,
                quantity: 10,
            },
            {
                id: 11,
                title: "Видеокарта EVGA GeForce RTX 3080 [10G-P5-3881-KR] [PCI-E 4.0 10 ГБ GDDR6X, 320 бит, HDMI, DP, GPU 1440 МГц]",
                oldPrice: 90000,
                newPrice: 85000,
                isPopular: true,
                sale: 5,
                brand: "EVGA",
                size: 5,
                quantity: 10,
            },
            {
                id: 12,
                title: "Видеокарта Zotac GeForce RTX 3090 [ZT-A30900D-10P] [PCI-E 4.0 24 ГБ GDDR6X, 384 бит, HDMI, DP, GPU 1395 МГц]",
                oldPrice: 160000,
                newPrice: 150000,
                isPopular: false,
                sale: 6,
                brand: "Zotac",
                size: 6,
                quantity: 10,
            }
        ]
    }),
    getters: {},
    actions: {},
})